// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PaperPark.Entity
{
    public partial class Category
    {
        public Category()
        {
            PaperModels = new HashSet<PaperModel>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PaperModel> PaperModels { get; set; }
    }
}