// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PaperPark.Entity
{
    public partial class PaperModel
    {
        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public string Name { get; set; }
        public int? NumOfSheet { get; set; }
        public int? Difficulty { get; set; }

        public virtual Category Category { get; set; }
    }
}